MYBOOKMS/urls.py
from django.conf.urls import  url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.urls import include

from bookapp import views

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'bookms.views.home', name='home'),
    # url(r'^bookms/', include('bookms.foo.urls')),



    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.welcome),
    url(r'^welcome$', views.welcome,name="welcome"),

    url(r'^accounts/index$', views.index,name="accounts_index"),
    url(r'^accounts/register$', views.register,name="register"),
    url(r'^accounts/login$', views.login,name="login"),
    url(r'^accounts/logout$', views.logout,name="logout"),
    url(r'^accounts/edit$', views.account_edit,name="edit"),
    url(r'^book/',include('bookapp.urls', namespace="book")),
]

urlpatterns += staticfiles_urlpatterns()

bookapp/urls.py
# -*- encoding: utf-8 -*-
# @Time    : 2018-03-19 21:06
# @Author  : mike.liu
# @File    : urls.py
from django.conf.urls import  url

from bookapp import views

app_name='book'
urlpatterns = [

    url(r'^create/$', views.create_book,name='create_book'),
    url(r'^list/$', views.list_book,name= 'list_book' ),
    url(r'^edit/(?P<id>[^/]+)/$', views.edit_book,name='edit_book'),
    url(r'^view/(?P<id>[^/]+)/$', views.view_book,name='view_book'),
    url(r'^manage/$', views.manage_book,name='manage_book'),
    url(r'^search/$', views.search_book,name='search_book'),
]

bookapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _ #引用国际化i18n

# Create your models here.
class Book(models.Model):
    class Meta:
        verbose_name = '图书'
        verbose_name_plural = verbose_name

    isbn = models.CharField('ISBN', max_length=13, unique=True)
    title = models.CharField('书名', max_length=200)
    subtitle = models.CharField('副标题', max_length=200, blank=True)
    pages = models.IntegerField('页数', blank=True)
    author = models.CharField('作者', max_length=60)
    translator = models.CharField('译者', max_length=60, blank=True)
    price = models.CharField('定价', max_length=60, blank=True)
    publisher = models.CharField('出版社', max_length=200, blank=True)
    pubdate = models.CharField('出版日期', max_length=60, blank=True)
    cover_img = models.URLField('封面图', blank=True)
    summary = models.TextField('内容简介', blank=True, max_length=2000)
    author_intro = models.TextField('作者简介', blank=True, max_length=2000)
    available = models.NullBooleanField ('是否可借', blank=True, default=True)
    create_time = models.DateField ('入库时间', auto_now_add=True)
    borrower = models.ForeignKey(User,verbose_name=_('借阅者'),on_delete=models.CASCADE, blank=True, null=True)
    borrow_date = models.DateField('借阅日期', blank=True, null=True)
    return_date = models.DateField('归还日期', blank=True, null=True)

    def __unicode__(self):
        return self.title
    def get_fields(self):
        # make a list of field/values.
        return [(field, field.value_to_string(self)) for field in Book._meta.fields]


class UserProfile(models.Model):
    class Meta:
        verbose_name = _('用户信息')
        verbose_name_plural = verbose_name
    user = models.OneToOneField(User, blank=True, null=True,related_name='user',on_delete=models.CASCADE)
    borrowed_book = models.ManyToManyField(Book,blank=True, null=True)
    def __unicode__(self):
        return self.user.username

bookapp/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# @Time    : 2018/3/19 16:30
# @Author  : mike.liu
# @File    : forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from bookapp.models import *


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ['borrower', 'available', 'borrow_date',
                   'return_date']  # uncomment this line and specify any field to exclude it from the form

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)


class AccountForm(forms.ModelForm):
    email = forms.EmailField(label=_("邮件"), max_length=30, widget=forms.TextInput(attrs={'size': 30, }))
    username = forms.CharField(label=_("昵称"), max_length=30, widget=forms.TextInput(attrs={'size': 20, }))
    password = forms.CharField(label=_("密码"), max_length=30, widget=forms.PasswordInput(attrs={'size': 20, }))

    def clean_username(self):
        '''验证重复昵称'''
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        raise forms.ValidationError(_("该昵称已经被使用请使用其他的昵称"))

    def clean_email(self):
        '''验证重复email'''
        emails = User.objects.filter(email__iexact=self.cleaned_data["email"])
        if not emails:
            return self.cleaned_data["email"]
        raise forms.ValidationError(_("该邮箱已经被使用请使用其他的"))

#注册信息的验证
class RegisterForm(forms.Form):
    email = forms.EmailField(label=_("邮件"),max_length=30,widget=forms.TextInput(attrs={'size':30,}))
    password = forms.CharField(label=_("密码"),max_length=30,widget=forms.PasswordInput(attrs={'size':20,}))
    newpassword = forms.CharField(label=_("确认密码"), max_length=30, widget=forms.PasswordInput(attrs={'size': 20, }))
    username = forms.CharField(label=_("昵称"),max_length=30,widget=forms.TextInput(attrs={'size':20,}))

    def clean_username(self):
        '''验证重复昵称'''
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        raise forms.ValidationError(_("该昵称已经被使用请使用其他的昵称"))

    def clean_email(self):
        '''验证重复email'''
        emails = User.objects.filter(email__iexact=self.cleaned_data["email"])
        if not emails:
            return self.cleaned_data["email"]
        raise forms.ValidationError(_("该邮箱已经被使用请使用其他的"))

    def clean_passwd(self):
        '''验证密码和确认密码是否一致'''
        cleaned_data = super(RegisterForm,self).clean()
        password = cleaned_data.get("password")
        newpassword = cleaned_data.get("newpassword")
        if password and newpassword:
            if password != newpassword:
                msg = "确认登录密码与登录密码不一致!"
                self._errors["newpassword"] = self.error_class([msg])

        return cleaned_data



class LoginForm(forms.Form):
    username=forms.CharField(label=_("昵称"),max_length=30,widget=forms.TextInput(attrs={'size':20,}))
    password=forms.CharField(label=_("密码"),max_length=30,widget=forms.PasswordInput(attrs={'size':20,}))

    def clean_username(self):
        '''验证用户名是否正确'''
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if  users:
            return self.cleaned_data["username"]
        raise forms.ValidationError(_("该用户不存在，请注册!"))

    def clean_password(self):
        '''验证密码是否正确'''
        password = User.objects.filter(password__iexact=self.cleaned_data["password"])
        if  not password:
            return self.cleaned_data["password"]
        raise forms.ValidationError(_("密码错误!"))

class SearchForm(forms.Form):
    query=forms.CharField(label=_("查询"),max_length=30,widget=forms.TextInput(attrs={'size':20,}))

bookapp/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login ,logout as auth_logout
from django.core.paginator import Paginator
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template.context_processors import csrf
from django.utils.translation import ugettext_lazy as _
from django.template import RequestContext
from django.template.loader import get_template
from django.contrib import auth
#首页，登录页，注册页面


from bookapp.forms import *


def welcome(request):
    #t = get_template('welcome.html')
    return HttpResponse(render(request, 'welcome.html'));

def index(request):
    '''首页视图'''
    template_var={"w":_("欢迎您 游客!")}
    if request.user.is_authenticated == True:
        template_var["w"]=_("欢迎您 %s!")%request.user.username

    return HttpResponse(render(request, 'success.html'));


'''注册视图'''
def register(request):
    template_var = {}
    form=RegisterForm()
    if request.method=="POST":
        form=RegisterForm(request.POST.copy())
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            newpassword = form.cleaned_data["newpassword"]
            email = form.cleaned_data["email"]
            #if password != newpassword:
               # return HttpResponse('确认登录密码与登录密码不一致');
            user = User.objects.create(email=email, password=password,username=username)
            user.save()
            #_login(request, username, password)  # 注册完毕 直接登陆
            return HttpResponseRedirect('/book/list/')
    template_var["form"] = form
    return HttpResponse(render(request,'registration/register.html',{'form':template_var["form"]}));



'''登录视图'''
def login(request):
    template_var = {}
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST.copy())
        if form.is_valid():
            if(True == _login(request,form.cleaned_data["username"],form.cleaned_data["password"])):
                return HttpResponseRedirect('/book/list/')
    #t=get_template('registration/login.html')
    #c = RequestContext(request, locals())

    template_var["form"] = form
    return HttpResponse(render(request, 'registration/login.html', {'form': template_var["form"]}));


'''登录核心方法'''
def _login(request,username,password):
    ret = False
    user = authenticate(username=username,password=password)
    if user:
        if user.is_active:
            auth_login(request,user)
            messages.add_message(request,messages.INFO,_('登录成功!'))
            ret = True
        else:
            messages.add_message(request,messages.INFO,_('登录失败!'))
    else:
        messages.add_message(request,messages.INFO,_('该用户不存在!'))
    return ret


'''def login(request):
    
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)  # 登录
            request.session['user'] = username  # 将 session 信息记录到浏览器
           # response = HttpResponseRedirect('/book/list/')
            return HttpResponseRedirect('/book/list/')
        else:
            return HttpResponse(render(request, 'registration/login.html', {'error': 'username or password error!'}))'''

'''注销视图'''
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/accounts/login')

'''编辑个人信息'''
def account_edit(request):
    try:
        account_instance = UserProfile.objects.get(id=request.user.id)
    except UserProfile.DoesNotExist:
        account_instance = None
    form = AccountForm(request.POST or None,instance=account_instance)
    if form.is_valid():
        form.save()
        form = AccountForm

    return HttpResponse(render(request, 'registration/account_edit.html',{'form': form}));



#================================================================================================
#书籍相关

'''创建书'''
def create_book(request):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = BookForm()
    return HttpResponse(render(request,'bookapp/create_book.html',{'form': form}))

'''图书列表'''
def list_book(request):
    list_items = Book.objects.all()
    paginator = Paginator(list_items,10)

    try:
        page = int(request.GET.get('page','1'))
    except ValueError:
        page = 1

    try:
        list_items = paginator.page(page)
    except:
        list_items = paginator.page(paginator.num_pages)

    return HttpResponse(render(request, 'bookapp/list_book.html'))

'''查找图书'''
def search_book(request,query):
    search_items = Book.objects.filter(title_contains=query)
    paginator = Paginator(search_items,10)
    try:
        page = int(request.GET.get('page','1'))
    except ValueError:
        page = 1
    try:
        search_items = paginator.page(page)
    except:
        search_items = paginator.page(paginator.num_pages)
    return HttpResponse(render(request, 'bookapp/search_book.html'))

'''管理图书信息'''
def manage_book(request):
    list_items = Book.objects.all()
    paginator = Paginator(list_items,10)

    try:
        page = int(request.GET.get('page','1'))
    except ValueError:
        page = 1

    try:
        list_items = paginator.page(page)
    except:
        list_items = paginator.page(paginator.num_pages)
    return HttpResponse(render(request, 'bookapp/manage_book.html'))

'''图书列表信息'''
def list_book(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST.copy())
        if form.is_valid():
            #if(True == _login(request,form.cleaned_data["username"],form.cleaned_data["password"])):
                return HttpResponseRedirect('/book/list/')

    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST.copy())
        if form.is_valid():
            email = form.cleaned_data["email"]
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = User.objects.create_user(username,email,password)
            user.save()
            #_login(request,username,password)  #注册完毕 直接登录
            return HttpResponseRedirect('/book/list/')

    form = SearchForm()
    if request.method == 'POST':
        form = SearchForm(request.POST.copy())
        if form.is_valid():
            query = form.cleaned_data["query"]
            search_items = Book.objects.filter(title__contains=query)

            paginator = Paginator(search_items,10)
            try:
                page = int(request.GET.get('page','1'))
            except ValueError:
                page = 1
            try:
                search_items = paginator.page(page)
            except:
                search_items = paginator.page(paginator.num_pages)
            return HttpResponse(render(request, 'bookapp/search_book.html'))

    list_items = Book.objects.all()
    paginator = Paginator(list_items,10)
    try:
        page = int(request.GET.get('page','1'))
    except ValueError:
        page = 1

    try:
        list_items = paginator.page(page)
    except :
        list_items = paginator.page(paginator.num_pages)
    return HttpResponse(render(request, 'bookapp/list_book.html'))

'''查看图书信息'''
def view_book(request,id):
    item = Book.objects.get(id=id)
    return HttpResponse(render(request, 'bookapp/view_book.html'))

'''编辑图书信息'''
def edit_book(request,id):
    book_instance = Book.objects.get(id=id)
    form = BookForm(request.POST or None,instance= book_instance)
    if form.is_valid():
        form.save()
    return HttpResponse(render(request, 'bookapp/edit_book.html'))

templates/bookapp/create_book.html
{% extends "book_base.html" %}

{% block title %} Book - Create {% endblock %}
{% block extrahead %}
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}js/douban/api.js"></script>
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}js/douban/api-parser.js"></script>
    <script language="javascript">
        $(document).ready(function(){
            $("#id_isbn").after("<span>输入10位或13位ISBN后回车，系统将自动获取图书信息</span>");
            $(":input").keypress(function(e) {
                var key = e.which;
                if (13 == key) {
                    e.preventDefault();
                    if(this.id=="id_isbn"){
                        fnFromDouban();
                    }
                    var index = $(":input").index(this);
                    {#                    var newIndex = index + 12;#}
                    {#                    $(":input:eq(" + index + ")").focus();#}
                }
            });
        });

        function fnFromDouban(){
            var reg=/^\d{10}|d{13}$/;
            if(!reg.test($("#id_isbn").val())){
                alert("正确的ISBN号应该为10位或13位！");
                return false;
            }
            DOUBAN.apikey = '00fa6c0654689a0202ef4412fd39ce06';
            DOUBAN.getISBNBook({
                isbn:$("#id_isbn").get(0).value,
                callback:function(bookinfo){
                    var list = DOUBAN.parseSubject(bookinfo);
                    if(list==null || list.length==0)
                    {
                        $("#id_isbn").focus();
                        alert("您要找的书的ISBN号不存在，请重新输入！");
                    }
                    else
                    {
                        $("#id_title").val(list.title ? list.title : "");
                        $("#id_summary").val(list.summary ? list.summary : "--");
                        $("#id_subtitle").val(list.attribute["subtitle"] ? list.attribute["subtitle"] : "--" );
                        $("#id_author").val(list.attribute["author"] ? list.attribute["author"] : "--" );
                        $("#id_translator").val(list.attribute["translator"] ? list.attribute["translator"]:"--" );
                        $("#id_pages").val(list.attribute["pages"] ? list.attribute["pages"] : "--" );
                        $("#id_price").val(list.attribute["price"] ? list.attribute["price"]: "--" );
                        $("#id_publisher").val(list.attribute["publisher"] ? list.attribute["publisher"] : "--" );
                        $("#id_pubdate").val(list.attribute["pubdate"] ? list.attribute["pubdate"] : "--" );
                        $("#id_cover_img").val(list.link.image);
                        $("#id_author_intro").val(list.attribute["author-intro"] ? list.attribute["author-intro"] : "--" );
                    }
                }
            })
            return true;
        }
    </script>
{% endblock %}
{% block heading %}<h1>  Book - Create </h1>  {% endblock %}
{% block content %}
    <table>
        <form action="" method="POST"> {% csrf_token %}
            {{form}}
            <tr>
                <td colspan="2" align="center"><input type="submit" value="Create"/></td>
            </tr>
        </form>
    </table>
{% endblock %}

templates/bookapp/edit_book.html
{% extends "book_base.html" %}

{% block title %} Book - Edit {% endblock %}

{% block heading %} <h1> Book</h1><h2> Edit </h2> {% endblock %}
{% block content %}
    <table class="table table-striped">
        <form action="" method="POST"> {% csrf_token %}
            {{form}}
            <tr>
                <td colspan="2" align="right"><input type="submit" value="Save"/></td>
            </tr>
        </form>
    </table>
{% endblock %}

templates/bookapp/list_book.html
{% extends "book_base.html" %}

{% block title %}
    图书列表
{% endblock %}

{% block content %}

    {% for item in list_items.object_list %}
        <div class="row">

            <div class="col-md-2">
                <br>
                <img src="{{item.cover_img}}"class="img-thumbnail img-center" />
            </div>

            <div class="col-md-8">
                <h4>{{item.title}}</h4>
                <br>
                <p>ISBN:{{item.isbn}}</p>
                <p>作者：{{item.author}}</p>
                <p>出版社：{{item.publisher}}</p>
            </div>
                <br>
                <div class="col-md-2 pull-right">
                   <p> <a class="btn btn-primary " href="{% url 'book:view_book' item.id %}"><i class="icon-check"></i> 详细 </a></p>
                    {% if item.available %}
                        <p><a class="btn btn-success" href="#"> <i class="icon-check"></i> 可借</a></p>
                    {% else %}
                        <p><a class="btn btn-danger" href="#"> <i class="icon-check"></i> 在外</a></p>
                    {% endif %}
                </div>


        </div>
        <hr>
    {% endfor %}
    <div class="row">
        {% if list_items.has_previous %}
            <a href="?page={{ list_items.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page {{ list_items.number }} of {{ list_items.paginator.num_pages }}.
        </span>

        {% if list_items.has_next %}
            <a href="?page={{ list_items.next_page_number }}">下一页</a>
        {% endif %}

    </div>
{% endblock %}

templates/bookapp/manage_book.html
{% extends "book_base.html" %}

{% block title %} 图书管理 {% endblock %}

{% block content %}
    {% for item in list_items.object_list %}
        <div class="row">
            <div class="col-md-2">
                <img src="{{item.cover_img}}"class="img-thumbnail img-center" />
            </div>
            <div class="col-md-3">
                <p>书名：{{item.title}}</p>
                <p>作者：{{item.author}}</p>
                <p>
                    <a class="btn btn-primary" href="{% url 'book:view_book' item.id %}"><span class=" icon-check icon-white" ></span>详细 </a>
                    <a class="btn btn-danger" href="{% url 'book:edit_book' item.id %}"> <span class=" icon-check icon-white" ></span>修改 </a>
                </p>
            </div>
            <div class="col-md-7">
                <p>简介：{{item.summary}}</p>
            </div>
        </div>
        <hr>
    {% endfor %}
    <div class="row">
        {% if list_items.has_previous %}
            <a href="?page={{ list_items.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
Page {{ list_items.number }} of {{ list_items.paginator.num_pages }}.
</span>

        {% if list_items.has_next %}
            <a href="?page={{ list_items.next_page_number }}">下一页</a>
        {% endif %}

    </div>
{% endblock %}

templates/bookapp/search_book.html
{% extends "book_base.html" %}

{% block title %}
    图书搜索
{% endblock %}

{% block content %}

    {% for item in search_items.object_list %}
        <div class="row">

            <div class="col-md-2">
                <br>
                <img src="{{item.cover_img}}"class="img-thumbnail img-center" />
            </div>

            <div class="col-md-8">
                <h4>{{item.title}}</h4>
                <br>
                <p>ISBN:{{item.isbn}}</p>
                <p>作者：{{item.author}}</p>
                <p>出版社：{{item.publisher}}</p>
            </div>
                <br>
                <div class="col-md-2 pull-right">
                   <p> <a class="btn btn-primary " href="{% url 'book:view_book' item.id %}"><i class="icon-check"></i> 详细 </a></p>
                    {% if item.available %}
                        <p><a class="btn btn-success" href="#"> <i class="icon-check"></i> 可借</a></p>
                    {% else %}
                        <p><a class="btn btn-danger" href="#"> <i class="icon-check"></i> 在外</a></p>
                    {% endif %}
                </div>


        </div>
        <hr>
    {% endfor %}
    <div class="row">
        {% if search_items.has_previous %}
            <a href="?page={{ search_items.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page {{ search_items.number }} of {{ search_items.paginator.num_pages }}.
        </span>

        {% if search_items.has_next %}
            <a href="?page={{ search_items.next_page_number }}">下一页</a>
        {% endif %}

    </div>
{% endblock %}

templates/bookapp/view_book.html
{% extends "book_base.html" %}

{% block title %} Book - View {% endblock %}

{% block heading %} <h1> Book</h1><h2>View</h2>  {% endblock %}

{% block extrahead %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-2 ">
            <div class="row">
                <img src="{{item.cover_img}}"class="img-thumbnail img-center" />
            </div>
            <br/><br/><br/>
            <canvas id="pie" width="120"></canvas>
            <p>借阅本书所占比例饼状图</p>
        </div>
        <div class="col-md-10">
            <table class="table table-condensed table-hover">
                {#                <thead>#}
                {#                <tr>#}
                {#                    <th>Student-ID</th>#}
                {#                    <th>First Name</th>#}
                {#                </tr>#}
                {#                </thead>#}
                <tbody>
                {% for field, value in item.get_fields %}
                    {% if field.name != 'cover_img' %}
                        <tr>
                            <td>{{ field.verbose_name }}</td>
                            <td> {{ value }} </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block extrafooter %}
    var pieData = [
    {
    value: 30,
    color:"#F38630"
    },
    {
    value : 150,
    color : "#69D2E7"
    }

    ];

    var myPie = new Chart(document.getElementById("pie").getContext("2d")).Pie(pieData);
{% endblock %}