MYBOOKMS/urls.py
from django.conf.urls import  url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.urls import include

from bookapp import views

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'bookms.views.home', name='home'),
    # url(r'^bookms/', include('bookms.foo.urls')),



    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.welcome),
    url(r'^welcome$', views.welcome,name="welcome"),

    url(r'^accounts/index$', views.index,name="accounts_index"),
    url(r'^accounts/register$', views.register,name="register"),
    url(r'^accounts/login$', views.login,name="login"),
    url(r'^accounts/logout$', views.logout,name="logout"),
    url(r'^accounts/edit$', views.account_edit,name="edit"),
    url(r'^book/',include('bookapp.urls', namespace="book")),
]

urlpatterns += staticfiles_urlpatterns()

bookapp/urls.py
# -*- encoding: utf-8 -*-
# @Time    : 2018-03-19 21:06
# @Author  : mike.liu
# @File    : urls.py
from django.conf.urls import  url

from bookapp import views

app_name='book'
urlpatterns = [

    url(r'^create/$', views.create_book,name='create_book'),
    url(r'^list/$', views.list_book,name= 'list_book' ),
    url(r'^edit/(?P<id>[^/]+)/$', views.edit_book,name='edit_book'),
    url(r'^view/(?P<id>[^/]+)/$', views.view_book,name='view_book'),
    url(r'^manage/$', views.manage_book,name='manage_book'),
    url(r'^search/$', views.search_book,name='search_book'),
]

templates/book_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet" />
    {#	<link href='http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600' rel='stylesheet'>#}
    <link href="/static/css/bootstrap.icon-large.min.css" rel="stylesheet">
    <link href="/static/css/jumbotron.css" rel="stylesheet">
    <link href="/static/css/offcanvas.css" rel="stylesheet">
    {% block extrahead %}{% endblock %}
    <style>
        p{
            font-family:'Microsoft Yahei', Helvetica, Arial, sans-serif;
        }

        label{
            font-family:'Microsoft Yahei', Helvetica, Arial, sans-serif;
        }

        canvas{
            float: left;
        }
    </style>


</head>

<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'welcome' %}">图书管理系统</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'book:list_book' %}">图书信息</a></li>
                <li><a href="{% url 'book:manage_book' %}">图书管理</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">我的图书馆 <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'edit' %}">个人资料</a></li>
                        <li class="divider"></li>
                        <li><a href="#">已借书籍</a></li>
                        <li class="divider"></li>
                        <li><a href="#">到期书籍</a></li>
                        <li class="divider"></li>
                        <li><a href="#">借阅历史</a></li>
                    </ul>
                </li>
            </ul>
            {#            <div class="navbar-right">#}
{#            <form class="form-inline pull-right navbar-form" role="search">#}
{#                <div class="form-group">#}
{#                    <input type="text" class="form-control" placeholder="Search">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default "> 搜 索 </button>#}
{#            </form>#}
            {#            </div>#}
            {% block loginmessage %}
                {% if request.user.is_authenticated %}
                    <div class="navbar-right">
                        <p class="navbar-text">欢迎您：<a href="#" class="navbar-link">{{ request.user.username }}</a></p>
                        <a href="{%url 'logout'%}" type="submit" class="btn btn-default navbar-btn">注 销</a>
                    </div><!--/.navbar-collapse -->
                {% else %}
                    <div class="navbar-right">
                        {#<a href="{%url 'login'%}" type="submit" class="btn btn-default navbar-btn" >登 陆</a>#}
                        <a class="btn btn-default navbar-btn"  data-toggle="modal" data-target="#LoginModal">登 陆</a>
                        {#                        <a href="{%url 'register'%}" type="submit" class="btn btn-default navbar-btn ">注 册</a>#}
                        <a class="btn btn-default navbar-btn"  data-toggle="modal" data-target="#RegisterModal">注 册</a>
                    </div><!--/.navbar-collapse -->
                {% endif %}
            {% endblock %}
        </div>

    </div>
</div>
<div class="container">

    <div class="row">

        <div class="col-md-9">
            {% block content %}
            {% endblock %}
        </div><!--/span-->
        <div class="col-md-3">
            <div class="row">


                <form class="form-inline pull-right" role="search" action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input  type="text" class="form-control"  name="query" placeholder="Search">
                    </div>
                    <button id="search_box" type="submit" class="btn btn-default"> 搜 索 </button>
                </form>


            </div>
            <br>
            <div class="row">
                <a class="btn btn-default pull-right" href="{% url 'book:create_book' %}">增加图书 </a>
            </div>
            <br/><br/><br/>

            <div class="col-md-13">
                <canvas id="line"></canvas>
                <p class="center pull-right">书籍数量/时间增长表</p>
            </div>
        </div><!--/span-->
    </div><!--/row-->
    <!-- LoginModal -->
    <div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="LoginModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="LoginModalLabel">请输入用户名和密码</h4>
                </div>
                <div class="modal-body">
                    <form class="margin-base-vertical" action="" method="post">
                        {% csrf_token %}
                        <p class="input-group">
                            <span class="input-group-addon"><span class="icon-user"></span></span>
                            <input type="text" class="form-control input-lg" name="username" placeholder="Jeremy" />
                        </p>

                        <p class="input-group">
                            <span class="input-group-addon"><span class="icon-lock"></span></span>
                            <input type="password" class="form-control input-lg" name="password"placeholder=""/>
                        </p>

                        <p class="help-block text-center">
                            <small>We won't send you spam. Unsubscribe at any time.</small>
                        </p>
                        <p class="text-center">
                            <button type="submit" class="btn btn-info btn-lg">登 陆</button>
                            <a class="btn btn-success btn-lg"href="{%url 'register'%}">注 册</a>
                        </p>
                    </form>
                    {% if form.errors %}
                        <p class="text-error">Sorry, that's not a valid username or password</p>
                    {% endif %}
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- RegisterModal -->
    <div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="RegisterModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="RegisterModalLabel">请输入用户名和密码</h4>
                </div>
                <div class="modal-body">
                    <form class="margin-base-vertical" action="" method="post">
                        {% csrf_token %}
                        <p class="input-group">
                            <span class="input-group-addon"><span class="icon-envelope"></span></span>
                            <input type="email" class="form-control input-lg" name="email"placeholder="jeremybaiit@gmail.com"/>
                        </p>

                        <p class="input-group">
                            <span class="input-group-addon"><span class="icon-user"></span></span>
                            <input type="text" class="form-control input-lg" name="username" placeholder="Jeremy" autocomplete="off" />
                        </p>

                        <p class="input-group">
                            <span class="input-group-addon"><span class="icon-lock"></span></span>
                            <input type="password" class="form-control input-lg" name="password"placeholder="" autocomplete="off"/>
                        </p>

                        <p class="help-block text-center">
                            <small>We won't send you spam. Unsubscribe at any time.</small>
                        </p>
                        <p class="text-center">
                            <button type="submit" class="btn btn-success btn-lg">注 册</button>
                            <a type="submit" class="btn btn-info btn-lg" href="{%url 'login'%}">登 陆</a>
                        </p>
                    </form>
                    {% if form.errors %}
                        <p class="text-error">Sorry, that's not a valid username or password</p>
                    {% endif %}
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <hr>

    <footer>
         <p class="pull-right"><a class="btn btn-default" href="#"><span class="glyphicon glyphicon-arrow-up"></span></a></p>
        <p>&copy; JeremyBai 2013</p>
    </footer>

</div><!--/.container-->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{#<script type="text/javascript" language="javascript" src="/static/js/jquery.js"></script>#}
{#<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>#}
<script type="text/javascript" language="javascript" src="/static/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" language="javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" language="javascript" src="/static/js/bootstrap-responsive.min.js"></script>
<script type="text/javascript" language="javascript" src="/static/js/Chart.min.js"></script>
<script>
    var lineChartData = {
        labels : ["January","February","March","April","May","June","July"],
        datasets : [
            {
                fillColor : "rgba(220,220,220,0.5)",
                strokeColor : "rgba(220,220,220,1)",
                pointColor : "rgba(220,220,220,1)",
                pointStrokeColor : "#fff",
                data : [65,59,90,81,56,55,40]
            },
            {
                fillColor : "rgba(151,187,205,0.5)",
                strokeColor : "rgba(151,187,205,1)",
                pointColor : "rgba(151,187,205,1)",
                pointStrokeColor : "#fff",
                data : [28,48,40,19,96,27,100]
            }
        ]

    }
    var myLine = new Chart(document.getElementById("line").getContext("2d")).Line(lineChartData);

{#     $(document).ready(function(){#}
{#            $("#search_box").click(function(e){#}
{#                alert("1");#}
{#                var query = $("#search_box").val();#}
{#                window.location.href="{% url "bookapp.views.welcome" %}";#}
{#            });#}
{#        });#}
    {% block extrafooter %}{% endblock %}
</script>

</body>
</html>

templates/login_base.html
<!DOCTYPE html>
<html>
<head>
    <meta name="generator"
          content="HTML Tidy for HTML5 (experimental) for Windows https://github.com/w3c/tidy-html5/tree/c63cc39" />
    <title>图书管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet" />

    {#	<link href='http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600' rel='stylesheet'>#}
    <link href="/static/css/bootstrap.icon-large.min.css" rel="stylesheet">
    <link href="/static/css/jumbotron.css" rel="stylesheet">

    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/offcanvas.css" rel="stylesheet">
    <link href="/static/css/bootstrap.icon-large.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600' rel='stylesheet'>

    <style>
        html {
            background: url(/static/img/6133364748_c34c5a1aaf_b.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        body {
            padding-top: 20px;
            font-size: 16px;
            font-family: "Open Sans",serif;
            background: transparent;
        }
        h1 {
            font-family: "Abel", Arial, sans-serif;
            font-weight: 400;
            font-size: 40px;
        }

        /* Override B3 .panel adding a subtly transparent background */
        .panel {
            background-color: rgba(255, 255, 255, 0.8);
        }
        .margin-base-vertical {
            margin: 40px 0;
        }

    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 panel panel-default">

            <h1 class="margin-base-vertical">Have you ever seen the rain?</h1>
            <p>Someone told me long ago there's a calm before the storm. I know, It's been comin for some time.</p>
            <p>When it's over, so they say, it'll rain a sunny day. I know, Shinin down like water.</p>
            <p>I want to know, have you ever seen the rain?</p>
            <hr/>
            {% block content %}{% endblock %}
            {% block errormessage %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/success.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <title></title>
</head>
<body>
      <h1>恭喜{{username}},注册成功!</h1>
</body>
</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/static/img/favicon.png">

    <title>BMS</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/bootstrap.icon-large.min.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="/static/css/carousel.css" rel="stylesheet">

    <style>
        {#        body{#}
        {#            background-color: #F8F8F8;#}
        {#        }#}
        p{
            font-family:'Microsoft Yahei', Helvetica, Arial, sans-serif;
        }

        label{
            font-family:'Microsoft Yahei', Helvetica, Arial, sans-serif;
        }
        a.bookname{
            text-decoration: none;
        }
    </style>
</head>
<!-- NAVBAR
================================================== -->
<body>
<br/><br/>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{%url 'welcome' %}">图书管理系统</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class=""><a href="{%url 'book:list_book' %}">图书信息</a></li>
                <li><a href="{%url 'book:manage_book' %}">图书管理</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">我的图书馆 <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{%url 'edit' %}">个人资料</a></li>
                        <li class="divider"></li>
                        <li><a href="#">已借书籍</a></li>
                        <li class="divider"></li>
                        <li><a href="#">到期书籍</a></li>
                        <li class="divider"></li>
                        <li><a href="#">借阅历史</a></li>
                    </ul>
                </li>
            </ul>
            {% block loginmessage %}
                {% if request.user.is_authenticated %}
                    <div class="navbar-right">
                        <p class="navbar-text">欢迎您：<a href="#" class="navbar-link">{{ request.user.username }}</a></p>
                        <a href="{%url 'logout'%}" type="submit" class="btn btn-default navbar-btn">注 销</a>
                    </div><!--/.navbar-collapse -->
                {% else %}
                    <div class="navbar-right">
                        {#<a href="{%url 'login'%}" type="submit" class="btn btn-default navbar-btn" >登 陆</a>#}
                        <a class="btn btn-default navbar-btn"  data-toggle="modal" data-target="#LoginModal">登 陆</a>
                        {#                        <a href="{%url 'register'%}" type="submit" class="btn btn-default navbar-btn ">注 册</a>#}
                        <a class="btn btn-default navbar-btn"  data-toggle="modal" data-target="#RegisterModal">注 册</a>
                    </div><!--/.navbar-collapse -->
                {% endif %}
            {% endblock %}
        </div>

    </div>
</div>

<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            {#            <img data-src="holder.js/900x500/auto/#777:#7a7a7a/text:First slide" alt="First slide">#}
            <img alt="" src="/static/img/pic1.jpg" />
            <div class="container">
                <div class="carousel-caption">
                    {#                    <h1>Example headline.</h1>#}
                    {#                    <h2>Only has compared to the others early, diligently diligently, canfeel the successful taste.</h2>#}
                    {#                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>#}
                </div>
            </div>
        </div>
        <div class="item">
            {#            <img data-src="holder.js/900x500/auto/#666:#6a6a6a/text:Second slide" alt="Second slide">#}
            <img alt="" src="/static/img/pic2.jpg" />
            <div class="container">
                <div class="carousel-caption">
                    {#                    <h1>Another example headline.</h1>#}
                    {#                    <h2>Nobody can casually succeed, it comes from the thoroughself-control and the will.</h2>#}
                    {#                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>#}
                </div>
            </div>
        </div>
        <div class="item">
            {#            <img data-src="holder.js/900x500/auto/#555:#5a5a5a/text:Third slide" alt="Third slide">#}
            <img alt="" src="/static/img/pic3.jpg" />
            <div class="container">
                <div class="carousel-caption">
                    {#                    <h1>One more for good measure.</h1>#}
                    {#                    <h2>Studies this matter, lacks the time, but is lacks diligently.</h2>#}
                    {#                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>#}
                </div>
            </div>
        </div>
        <div class="item">
            {#            <img data-src="holder.js/900x500/auto/#555:#5a5a5a/text:Third slide" alt="Third slide">#}
            <img alt="" src="/static/img/pic4.jpg" />
            <div class="container">
                <div class="carousel-caption">
                    {#                    <h1>One more for good measure.</h1>#}
                    {#                    <h2>Studies this matter, lacks the time, but is lacks diligently.</h2>#}
                    {#                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>#}
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-lg-4">
            <img class="img-circle" src="/static/img/linuxtux.jpg" alt="Generic placeholder image">
            <h2>Tux</h2>
            <p>Linux则常用来指基于Linux内核的完整操作系统，包括GUI组件和许多其他实用工具。由于这些支持用户空间的系统工具
                和库主要由理查德·斯托曼于1983年发起的GNU计划提供，自由软件基金会提议将该组合系统命名为“GNU/Linux”。</p>
            {#            <p><a class="btn btn-default" href="http://zh.wikipedia.org/wiki/Linux" role="button">View details &raquo;</a></p>#}
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle" src="/static/img/FreeBSD.jpg" alt="Generic placeholder image">
            <h2>Daemon</h2>
            <p>FreeBSD是一种自由的类Unix操作系统，是由经过BSD、386BSD和4.4BSD发展而来的类Unix的一个重要分支。
                FreeBSD拥有超过200名活跃开发者和上千名贡献者。FreeBSD被认为是自由操作系统中的不知名的巨人。
                它不是Unix，但如Unix一样运行，兼容POSIX。作为一个操作系统，FreeBSD被认为相当稳健可靠。</p>
            {#            <p><a class="btn btn-default" href="http://zh.wikipedia.org/wiki/Freebsd#" role="button">View details &raquo;</a></p>#}
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle" src="/static/img/Javaduke.jpg" alt="Generic placeholder image">
            <h2>Duke</h2>
            <p>Java是一种计算机编程语言，拥有跨平台、面向对象、泛型编程的特性，广泛应用于企业级Web应用开发和移动应用开发。</p>
            {#            <p><a class="btn btn-default" href="http://zh.wikipedia.org/wiki/Java" role="button">View details &raquo;</a></p>#}
        </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->

    <div class="row">
        <div class="col-lg-4">
            <p><a class="btn btn-default" href="http://zh.wikipedia.org/wiki/Linux" role="button">View In Wiki &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <p><a class="btn btn-default" href="http://zh.wikipedia.org/wiki/Freebsd#" role="button">View In Wiki &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <p><a class="btn btn-default" href="http://zh.wikipedia.org/wiki/Java" role="button">View In Wiki &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-6">
            <h2 class="featurette-heading"><a class="bookname" href="/bookapp/book/view/3/">飘</a><span class="text-muted"></span></h2>
            <br/>
            <p class="lead">小说中的故事发生在1861年美国南北战争前夕。生活在南方的少女郝思嘉从小深受南方文化传统
                的熏陶，可在她的血液里却流淌着野性的叛逆因素。随着战火的蔓廷和生活环境的恶化，郝思嘉的叛逆个性越来
                越丰满，越鲜明，在一系列的的挫折中她改造了自我，改变了个人甚至整个家族的命运，成为时代时势造就的新
                女性的形象。</p>
        </div>
        <div class="col-md-6">
            <img class="featurette-image img-responsive img-rounded" src="/static/img/gonewithwind.jpg" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-6">
            <img class="featurette-image img-responsive img-rounded" src="/static/img/hongloumeng.jpg" alt="Generic placeholder image">
        </div>
        <div class="col-md-6">
            <h2 class="featurette-heading"><a class="bookname" href="/bookapp/book/view/4/">红楼梦</a><span class="text-muted"></span></h2>
            <br/>
            <p class="lead">《红楼梦》是一部百科全书式的长篇小说。以宝黛爱情悲剧为主线，以四大家族的荣辱兴衰为背景，
                描绘出18世纪中国封建社会的方方面面，以及封建专制下新兴资本主义民主思想的萌动。结构宏大、情节委婉、
                细节精致，人物形象栩栩如生，声口毕现，堪称中国古代小说中的经典。</p>
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-6">
            <h2 class="featurette-heading"><a class="bookname" href="/bookapp/book/view/5/"> 傲慢与偏见</a><span class="text-muted"></span></h2>
            <br/>
            <p class="lead">《傲慢与偏见》是英国著名女作家简·奥斯汀（Jane Austen 1775～1817年）的代表作，
                是一部描写爱情与婚姻的小说。这部小说以男女主人公达西和伊丽莎白由于傲慢和偏见而产生的爱情纠葛为线索......
            </p>
        </div>
        <div class="col-md-6">
            <img class="featurette-image img-responsive img-rounded" src="/static/img/PrideandPrejudice.jpg" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->


    <!-- FOOTER -->
    <footer>
        <p class="pull-right"><a class="btn btn-default" href="#"><span class="glyphicon glyphicon-arrow-up"></span></a></p>
        {#        <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>#}
        <p>&copy; JeremyBai 2013</p>
    </footer>

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/holder.js"></script>
</body>
</html>